# .github/workflows/docker-deploy.yml
name: test

on:
  push:
    branches:
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.10.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # secrets转环境变量
      - name: Secrets To Env Var
        id: secretsToEnvVar
        run: |
          echo "ENV_NAME=dev" >> "$GITHUB_ENV"
          echo "DEV_DOCKER_LOGIN_USERNAME=${{secrets.DEV_DOCKER_LOGIN_USERNAME}}" >> "$GITHUB_ENV"
          echo "DEV_DOCKER_LOGIN_PASSWORD=${{secrets.DEV_DOCKER_LOGIN_PASSWORD}}" >> "$GITHUB_ENV"
          echo "DEV_DOCKER_IMAGE_URL=${{secrets.DEV_DOCKER_IMAGE_URL}}" >> "$GITHUB_ENV"
          echo "DEV_DOCKER_IMAGE_URL_NAME=${{secrets.DEV_DOCKER_IMAGE_URL_NAME}}" >> "$GITHUB_ENV"
          echo "DEV_SSH_HOST=${{secrets.DEV_SSH_HOST}}" >> "$GITHUB_ENV"
          echo "DEV_SSH_USER=${{secrets.DEV_SSH_USER}}" >> "$GITHUB_ENV"
          echo "DEV_SSH_PW=${{secrets.DEV_SSH_PW}}" >> "$GITHUB_ENV"
          echo "DEV_SSH_PORT=${{secrets.DEV_SSH_PORT}}" >> "$GITHUB_ENV"
      #
      # 输出环境变量
      - name: Echo Env Var
        id: echoEnvVar
        run: |
          echo "${ENV_NAME}"
          echo "${DEV_DOCKER_LOGIN_USERNAME}"
          echo "${DEV_DOCKER_LOGIN_PASSWORD}"
          echo "${DEV_DOCKER_IMAGE_URL}"
          echo "${DEV_DOCKER_IMAGE_URL_NAME}"
          echo "${DEV_SSH_HOST}"
          echo "${DEV_SSH_USER}"
          echo "${DEV_SSH_PW}"
          echo "${DEV_SSH_PORT}"
